version: '3.9'

services:
  api:
    build: ./api
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./web
    expose:
      - 5000
    env_file:
      - .frontend.env
    volumes:
      - ./web/webapp/static/:/app/webapp/static/

  nginx:
    build: ./nginx
    ports:
     - 80:80
    depends_on:
      - frontend
    volumes:
      - ./web/webapp/static/:/app/static/

  postgres:
    image: 'postgres:14.5-alpine'
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "labo", "-U", "student_password" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - postgres:/var/lib/postgresql/data/

volumes:
  postgres:
